# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BOA-Computing
logo: "/pics/boa2CS.png"
email: boa.cp.ltd@gmail.com
description: Multidisciplinary medical-oriented R&D service
keywords: "Software Engineering, Mathematics, Physics, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Algorithms, Numerical methods"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.boa-cp.com" # the base hostname & protocol for your site
#twitter_username: b
github_username:  boa-cp

# Build settings
markdown: kramdown

collections:
  articles:	
    output: true
  downloads:
    output: true
  examples:
    output: true

